version: 0.2
            
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete dist "s3://cms-site.uk"
cache:
  paths:
    - node_modules/**/*