version: 0.2
            
phases:
  install:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - "**/*"
  base-directory: dist
cache:
  paths:
    - node_modules/**/*